import "src/reviews/set_rating.js"
import "src/reviews/preview_image.js"
import "stylesheets/reviews/new.scss"
import "stylesheets/reviews/poster_form.scss"
import "stylesheets/shared/review_rating.scss"
