version: '3'
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  storage:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - .:/wan_family
      - /wan_family/log
      - /wan_family/tmp
      - /wan_family/.git
      - ./tmp/screenshots:/wan_family/tmp/screenshots
      - vendor_bundle:/wan_family/vendor/bundle
      - node_modules:/wan_family/node_modules
      - storage:/wan_family/storage
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
  chrome:
    image: selenium/standalone-chrome:102.0.5005.61-chromedriver-102.0.5005.61
    ports:
      - "4444:4444"
