version: '3'
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  storage:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - .:/wan_family
      - /wan_family/log
      - /wan_family/tmp
      - vendor_bundle:/wan_family/vendor/bundle
      - node_modules:/wan_family/node_modules
      - storage:/wan_family/storage
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0

    # volumes:
    #   - .:/wan_family
      # https://qiita.com/shotat/items/57d049793605ffc20135
      # ホストからマウントする必要のないディレクトリを別のvolumeでマウントを上書き

    # networksを設定してネットワークを共有することで、複数のdocker-compose間での接続が可能になる
    # networks:
    #   - default
