version: 2.1
orbs:
  build-tools: circleci/build-tools@2.6.3
  node: circleci/node@5.1.0
  ruby: circleci/ruby@1.1.2

jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.4-node
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wan_family_test
          MYSQL_USER: root
      - image: selenium/standalone-chrome:102.0.5005.61-chromedriver-102.0.5005.61
        name: chrome
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
      APP_NAME: Wan Family
      WEB_PROTOCOL: http
      WEB_HOST: localhost:3000
    working_directory: ~/wan_family
    steps:
      - checkout:
          path: ~/wan_family
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: Webpacker Compile
          command: bundle exec rake assets:precompile
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - run:
          name: Rspec
          command: bundle exec rspec

  deploy:
    docker:
      - image: cimg/ruby:3.1.4-node
    working_directory: ~/wan_family
    steps:
      - checkout
      - build-tools/install-ci-tools
      - add_ssh_keys:
          fingerprints:
            - 7a:7a:27:66:80:8c:7b:8f:05:b4:4e:83:9a:d8:65:f7
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Capistrano deploy
          command: bundle exec cap production deploy BRANCH=feature22/aws_deploy

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          # filters:
          #   branches:
          #     only: master
