version: 2.1
orbs:
  build-tools: circleci/build-tools@2.6.3
  jq: circleci/jq@1.9.1
  node: circleci/node@5.1.0
  ruby: circleci/ruby@1.1.2

jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.4-node
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wan_family_test
          MYSQL_USER: root
      - image: selenium/standalone-chrome:102.0.5005.61-chromedriver-102.0.5005.61
        name: chrome
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
      APP_NAME: Wan Family
      WEB_PROTOCOL: http
      WEB_HOST: localhost:3000
    working_directory: ~/wan_family
    steps:
      - checkout:
          path: ~/wan_family
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: Webpacker Compile
          command: bundle exec rake assets:precompile
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - run:
          name: Rspec
          command: bundle exec rspec

  deploy:
    working_directory: ~/wan_family
    docker:
      - image: sue445/heroku-cli
    environment:
      RAILS_ENV: production
    steps:
      - checkout
      - build-tools/install-ci-tools
      - jq/install
      - run:
          name: Identify who I am
          command: echo 'export MY_EMAIL=`heroku auth:whoami | tail -n 1`' >> $BASH_ENV
      - run:
          name: Identify created heroku app name
          command: echo 'export CREATED_APP_NAME=`heroku apps --json | jq -r "map(select(.owner.email == "\"$MY_EMAIL\"" and (.name | contains(\"$HEROKU_APP_NAME\")))) | .[].name"`' >> $BASH_ENV
      - run:
          name: Create and set up new apps if needed
          command: |
            if [ "$HEROKU_APP_NAME" != "$CREATED_APP_NAME" ]; then \
              heroku apps:create $HEROKU_APP_NAME --addons=jawsdb:kitefin; \
              heroku config:set RAILS_MASTER_KEY=$RAILS_MASTER_KEY -a $HEROKU_APP_NAME; \
            fi
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
      - run:
          name: Set up Database
          command: |
            heroku run bin/rails db:migrate -a $HEROKU_APP_NAME
            heroku run bin/rails db:seed_fu -a $HEROKU_APP_NAME

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      # - test
      - deploy
      # - deploy:
      #     requires:
      #       - test
          # filters:
          #   branches:
          #     only: master
