import "src/shared/display_rating.js"
import "src/shared/hidden_card.js"
import "stylesheets/users/review_index.scss"
import "stylesheets/images/enlarged_image.scss"
import "stylesheets/shared/review_rating.scss"
import "stylesheets/shared/review_content.scss"
import "stylesheets/shared/sort_link.scss"
