import "src/shared/display_image_slide.js"
import "src/shared/display_rating.js"
import "stylesheets/users/spot_favorite_index.scss"
import "stylesheets/users/mypage.scss"
import "stylesheets/shared/spot_list.scss"
import "stylesheets/shared/review_rating.scss"
